dev:
  image: hgezim/wp-nocache:2.1
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - /Users/gezimhome/projects/ziprecipes.net/zip-recipes/src:/var/www/html/wp-content/plugins/zip-recipes

db:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: root
